services:
  api:
    container_name: secureherai_api
    build:
      context: ./secureherai-api
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./secureherai-api:/app
      - maven_cache:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev
    ports:
      - "8080:8080"
    env_file:
      - ./secureherai-api/.env
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/secureherai
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: dev

      # JWT Configuration
      JWT_SECRET: HRVu1xFYfraq/lculzNaXzMHVady85sMReuLwlSzEjcKznYOEPdbbK3F+9hq+4muGxhYfft5nNQYxbDZIGzzAA==
      JWT_EXPIRATION: 86400000 # Email Configuration (Use environment variables for production)
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}

      # OAuth2 Configuration
      OAUTH2_WEB_ORIGIN: ${OAUTH2_WEB_ORIGIN:-}
      OAUTH2_WEB_REDIRECT_URI: ${OAUTH2_WEB_REDIRECT_URI:-}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID:-}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET:-}
      OAUTH2_CLIENT_ID_ANDROID: ${OAUTH2_CLIENT_ID_ANDROID:-}
        # Debugging settings
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      SPRING_BOOT_LOGGING_LEVEL: DEBUG
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - app-network  # Frontend web application (React Native Expo)
  frontend:
    container_name: secureherai_web
    build:
      context: ./secureherai-app
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./secureherai-app:/app
      - node_modules:/app/node_modules
      - expo_cache:/app/.expo
    working_dir: /app
    command: sh -c "CI=1 npx expo start --web --host lan --port 19006"
    ports:
      - "19006:19006"
    environment:
      EXPO_PUBLIC_API_BASE_URL: http://api:8080
      NODE_ENV: development
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      CI: "1"
      EXPO_USE_FAST_REFRESH: "true"
      EXPO_USE_METRO_CACHE: "false"
      EXPO_NO_DOTENV: "1"
      EXPO_NO_TELEMETRY: "1"
      EXPO_NO_UPDATE_CHECK: "1"
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

  db:
    container_name: postgres_secureherai
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secureherai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d secureherai"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

volumes:
  postgres_data:
  maven_cache:
  node_modules:
  expo_cache:

networks:
  app-network:
    driver: bridge
    name: app-network
    # external: true

# For pgAdmin (http://localhost:5050):

# Email: admin@admin.com
# Password: root
# Then add a new server with:

# Name: SecureHerAI DB
# Host: postgres_secureherai (container name)
# Port: 5432
# Database: secureherai
# Username: user
# Password: password
