version: "3.8"

services:
  api:
    image: secureherai-api-api
    container_name: secureherai_api
    # no bind-mount
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/secureherai
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: dev

        # JWT Configuration
      JWT_SECRET: HRVu1xFYfraq/lculzNaXzMHVady85sMReuLwlSzEjcKznYOEPdbbK3F+9hq+4muGxhYfft5nNQYxbDZIGzzAA==
      JWT_EXPIRATION: 86400000 # Email Configuration (Use environment variables for production)
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}

      # OAuth2 Configuration
      OAUTH2_WEB_ORIGIN: ${OAUTH2_WEB_ORIGIN:-}
      OAUTH2_WEB_REDIRECT_URI: ${OAUTH2_WEB_REDIRECT_URI:-}

      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID:-}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET:-}

      OAUTH2_CLIENT_ID_ANDROID: ${OAUTH2_CLIENT_ID_ANDROID:-}
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres_secureherai
    # … keep as before
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
