version: "3.8"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  api:
    container_name: secureherai_api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/secureherai
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_PROFILES_ACTIVE: dev

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-}

      # Email Configuration (Use environment variables for production)
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}

      # OAuth2 Web Configuration
      OAUTH2_WEB_ORIGIN: ${OAUTH2_WEB_ORIGIN:-}
      OAUTH2_WEB_REDIRECT_URI: ${OAUTH2_WEB_REDIRECT_URI:-}

      # OAuth2 Credential Configuration
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID:-}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET:-}
      OAUTH2_CLIENT_ID_ANDROID: ${OAUTH2_CLIENT_ID_ANDROID:-}

      # Azure Speech Service Configuration
      AZURE_SPEECH_KEY: ${AZURE_SPEECH_KEY:-}
      AZURE_SPEECH_REGION: ${AZURE_SPEECH_REGION:-}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/api/isOk"]
      interval: 170s
      timeout: 10s
      retries: 3
      start_period: 180s
    stdin_open: true
    tty: true
    networks:
      - app-network

  db:
    container_name: postgres_secureherai
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secureherai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d secureherai"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

volumes:
  postgres_data:
  maven_cache:

networks:
  app-network:
    driver: bridge
    name: app-network
    # external: true
# For pgAdmin (http://localhost:5050):

# Email: admin@admin.com
# Password: root
# Then add a new server with:

# Name: SecureHerAI DB
# Host: postgres_secureherai (container name)
# Port: 5432
# Database: secureherai
# Username: user
# Password: password
