name: Create Production Builds and Deploy Web

on:
  push:
    branches: ['amin']

jobs:
  deploy_web:
    name: Deploy Web
    type: deploy
    environment: production
    run: |
      npm test
    params:
      prod: true