name: Create Production Builds and Deploy Web

on:
  push:
    branches: ['main','amin']

jobs:
  deploy_web:
    name: Deploy Web
    type: deploy
    environment: production
    params:
      prod: true
      
  build_android:
    name: Build Android
    type: build
    params:
      platform: android