name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AZURE_VM_SSH_PRIVATE_KEY }}

      - name: Add Azure VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.AZURE_VM_HOST }} >> ~/.ssh/known_hosts

      - name: Ensure remote Docker network exists
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} \
            "docker network create app-network || true"

      - name: Create & use Docker context for Azure VM
        run: |
          docker context create azure-vm \
            --docker "host=ssh://${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}"
          docker context use azure-vm

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose-dev.yml down || true
          docker compose -f docker-compose-dev.yml pull
          docker compose -f docker-compose-dev.yml up --build -d

      - name: Verify deployment
        run: docker compose -f docker-compose-dev.yml ps

      - name: Reset Docker context
        if: always()
        run: |
          docker context use default
          docker context rm azure-vm
