name: Test SecureHerAI Application

on:
  push:
    branches:
      - main
      - amin
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Make Maven wrapper executable
        working-directory: secureherai-api
        run: chmod +x mvnw

      - name: Run backend unit tests
        working-directory: secureherai-api
        run: ./mvnw clean test

      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: secureherai-api/target/surefire-reports/

      - name: Verify test results
        working-directory: secureherai-api
        run: |
          echo "Test execution completed."
          if [ -d "target/surefire-reports" ]; then
            echo "Test reports generated successfully."
          else
            echo "Test reports not found."
            exit 1
          fi

  test-frontend:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: secureherai-app/package-lock.json

      - name: Install frontend dependencies
        working-directory: secureherai-app
        run: npm ci

      - name: Run frontend tests
        working-directory: secureherai-app
        run: npm run test:ci

      - name: Upload frontend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: frontend-test-results
          path: secureherai-app/coverage/

      - name: Verify frontend test results
        working-directory: secureherai-app
        run: |
          echo "Frontend test execution completed."
          if [ -d "coverage" ]; then
            echo "Coverage reports generated successfully."
          else
            echo "Coverage reports not found."
          fi
