name: Test SecureHerAI Application

on:
  push:
    branches:
      - main
      - ans2003
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run backend unit tests
        working-directory: secureherai-api
        run: ./mvnw clean test

      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: secureherai-api/target/surefire-reports/

      - name: Verify test results
        working-directory: secureherai-api
        run: |
          echo "Test execution completed."
          if [ -d "target/surefire-reports" ]; then
            echo "Test reports generated successfully."
          else
            echo "Test reports not found."
            exit 1
          fi
