name: Test SecureHerAI Application

on:
  push:
    branches: [ans2003]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    name: Backend Unit Tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Run backend unit tests
        working-directory: secureherai-api
        run: ./mvnw clean test

      - name: Upload backend test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: backend-test-results
          path: secureherai-api/target/surefire-reports/

  test-summary:
    runs-on: ubuntu-latest
    name: Test Summary
    needs: [backend-tests]
    if: always()

    steps:
      - name: Test Results Summary
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Backend Unit Tests: ${{ needs.backend-tests.result }}" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ needs.backend-tests.result }}" == "success" ]]; then
            echo "✅ Backend tests passed! Ready for deployment." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Backend tests failed. Please check the logs." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
